version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/myapp
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - .env
    networks:
      - default

volumes:
  db_data: